# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
---
theme:
  name: material # bootstrap386
  favicon: assets/rehack.ico
  icon:
    logo: material/ghost-outline
  nav_style: dark
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
  features:
    - content.code.annotate

site_name: Hyeokjin's Biography

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/hyeokjin/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk
    - icon: octicons/mark-github-16
      link: https://github.com/H-Kwon

copyright: Copyright &copy; Since 2022 Hyeokjin Kwon

markdown_extensions:
  # Python Markdown
  - abbr
  - footnotes
  - meta
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - admonition
  - def_list

  # Python Markdown Extensions
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css
...
